export const Images = { 
  logo: require('../../public/Assets/Images/logo.svg'), 
  dotsbg: require('../../public/Assets/Images/dotsbg.png'), 
  bgright: require('../../public/Assets/Images/bgright.png'), 
  bgbottom: require('../../public/Assets/Images/bgbottom.png'), 
  featuredOne: require('../../public/Assets/Images/featuredOne.svg'), 
  featuredTwo: require('../../public/Assets/Images/featuredTwo.svg'), 
  featuredThree: require('../../public/Assets/Images/featuredThree.svg'), 
  featuredFour: require('../../public/Assets/Images/featuredFour.svg'), 
  featuredFive: require('../../public/Assets/Images/featuredFive.svg'), 
  featuredSix: require('../../public/Assets/Images/featuredSix.svg'), 
  platformOne: require('../../public/Assets/Images/platformOne.jpg'),
  platformTwo: require('../../public/Assets/Images/platformTwo.jpg'),
  platformThree: require('../../public/Assets/Images/platformThree.jpg'),
  platformFour: require('../../public/Assets/Images/platformFour.jpg'),
  platformFive: require('../../public/Assets/Images/platformFive.jpg'),
  platformSix: require('../../public/Assets/Images/platformSix.jpg'),
  platformSeven: require('../../public/Assets/Images/platformSeven.jpg'),
  platformEight: require('../../public/Assets/Images/platformEight.jpg'),
  platformNine: require('../../public/Assets/Images/platformNine.jpg'),
};  